CREATE TABLE [dbo].[FIELDS] (
    [FIELDID]    INT           IDENTITY (1, 1) NOT NULL,
    [SYSTEMID]   INT           NOT NULL,
    [ENTITYNAME] VARCHAR (200) NOT NULL,
    [FIELDNAME]  VARCHAR (200) NOT NULL,
    PRIMARY KEY CLUSTERED ([FIELDID] ASC),
    FOREIGN KEY ([SYSTEMID]) REFERENCES [dbo].[SYSTEM] ([ID])
);

