CREATE TABLE [dbo].[FIELDCODES] (
    [CODEID]    INT           IDENTITY (1, 1) NOT NULL,
    [FIELDID]   INT           NOT NULL,
    [CODEVALUE] VARCHAR (200) NULL,
    PRIMARY KEY CLUSTERED ([CODEID] ASC),
    FOREIGN KEY ([FIELDID]) REFERENCES [dbo].[FIELDS] ([FIELDID])
);

