CREATE TABLE [dbo].[INTEGRATION_LEGALENTITIES] (
    [ID]              INT IDENTITY (1, 1) NOT NULL,
    [INTEGRATION_ID]  INT NOT NULL,
    [LEGAL_ENTITY_ID] INT NOT NULL,
    [IS_ACTIVE]       BIT CONSTRAINT [DF_INTEGRATION_LEGALENTITIES_IS_ACTIVE] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_INTEGRATION_LEGALENTITIES] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_INTEGRATION_LEGALENTITIES_FUNCTION] FOREIGN KEY ([INTEGRATION_ID]) REFERENCES [dbo].[INTEGRATION] ([ID]),
    CONSTRAINT [FK_INTEGRATION_LEGALENTITIES_LEGAL_ENTITY] FOREIGN KEY ([LEGAL_ENTITY_ID]) REFERENCES [dbo].[LEGAL_ENTITY] ([ID])
);

