CREATE TABLE [dbo].[INTEGRATION] (
    [ID]               INT           IDENTITY (1, 1) NOT NULL,
    [INTEGRATION_NAME] VARCHAR (200) NULL,
    CONSTRAINT [INTEGRATION_pk] PRIMARY KEY NONCLUSTERED ([ID] ASC)
);

