CREATE TABLE [dbo].[LEGAL_ENTITY] (
    [ID]           INT          IDENTITY (1, 1) NOT NULL,
    [COUNTRY_ID]   INT          NOT NULL,
    [LEGAL_ENTITY] VARCHAR (50) NOT NULL,
    CONSTRAINT [LegalEntity_pk] PRIMARY KEY NONCLUSTERED ([ID] ASC),
    CONSTRAINT [FK_LEGAL_ENTITY_COUNTRY] FOREIGN KEY ([COUNTRY_ID]) REFERENCES [dbo].[COUNTRY] ([ID])
);

