CREATE TABLE [dbo].[MAPPINGS] (
    [MAPPINGID]     INT IDENTITY (1, 1) NOT NULL,
    [INTEGRATIONID] INT NOT NULL,
    [FIELDID1]      INT NOT NULL,
    [CODEID1]       INT NOT NULL,
    [FIELDID2]      INT NOT NULL,
    [CODEID2]       INT NOT NULL,
    PRIMARY KEY CLUSTERED ([MAPPINGID] ASC),
    FOREIGN KEY ([CODEID1]) REFERENCES [dbo].[FIELDCODES] ([CODEID]),
    FOREIGN KEY ([CODEID2]) REFERENCES [dbo].[FIELDCODES] ([CODEID]),
    FOREIGN KEY ([FIELDID1]) REFERENCES [dbo].[FIELDS] ([FIELDID]),
    FOREIGN KEY ([FIELDID2]) REFERENCES [dbo].[FIELDS] ([FIELDID]),
    FOREIGN KEY ([INTEGRATIONID]) REFERENCES [dbo].[INTEGRATION] ([ID])
);

